export const USER_AUTH_SUCCESS = "USER:AUTH_SUCCESS";
export const USER_AUTH_FAIL = "USER:AUTH_FAIL";
export const USER_AUTH_LOGOUT = "USER:AUTH_LOGOUT";
export const USER_UPDATE_PROFILE = "USER:UPDATE_PROFILE";
export const USER_UPLOAD_AVATAR = "USER:UPLOAD_AVATAR";
export const USER_RESET_SUCCESS = "USER:RESET_SUCCESS";
export const USER_RESET_FAIL = "USER:RESET_FAIL";

export const PAYMENT_GET_PAYMENT = "PAYMENT:GET_PAYMENT";
export const PAYMENT_GET_STATUS = "PAYMENT:GET_STATUS";

export const INVITE_GET_USERS = "INVITE:GET_USERS";
export const INVITE_GET_MANAGER = "INVITE:GET_MANAGER";
export const INVITE_GET_STATS = "INVITE:GET_STATS";

export const GET_CONFERENCE_FAIL = "CONFERENCE:GET_LIVE_FAIL";
export const GET_CONFERENCE_SUCCESS = "CONFERENCE:GET_LIVE_SUCCESS";

export const GET_CONFERENCES = "ARCHIVE:GET_CONFERENCES";

export const LANDING_GET_LANDINGS = "LANDING:GET_LANDINGS";
export const LANDING_GET_REQUESTS = "LANDING:GET_REQUESTS";
export const LANDING_SET_LANDING = "LANDING:SET_LANDING";

export const ADD_MESSAGE = "CHAT:ADD_MESSAGE";
export const DELETE_MESSAGE = "CHAT:DELETE_MESSAGE";
export const SET_MESSAGES = "CHAT:SET_MESSAGES";
export const SET_USERS = "CHAT:SET_USERS";
export const SET_USERS_SECTION = "CHAT:SET_USERS_SECTION";
export const ONLINE_USER = "CHAT:ONLINE_USER";
export const OFFLINE_USER = "CHAT:OFFLINE_USER";
export const BLOCK_USER = "CHAT:BLOCK_USER";
export const CHAT_FAIL = "CHAT:CHAT_FAIL";
