export const USER_POST_SUCCESS = "USER:POST_SUCCESS";
export const USER_POST_FAIL = "USER:POST_FAIL";

export const USER_GET_SUCCESS = "USER:GET_SUCCESS";
export const USER_GET_FAIL = "USER:GET_FAIL";

export const USER_UPDATE_SUCCESS = "USER:UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER:UPDATE_FAIL";

export const FOOD_NEAREST_START = "FOOD:GET_NEAREST_START";
export const FOOD_NEAREST_SUCCESS = "FOOD:GET_NEAERST_SUCCESS";
export const FOOD_NEAREST_FAIL = "FOOD:GET_NEAERST_FAIL";

export const FOOD_OWN_START = "FOOD:GET_OWN_START";
export const FOOD_OWN_SUCCESS = "FOOD:GET_OWN_SUCCESS";
export const FOOD_OWN_FAIL = "FOOD:GET_OWN_FAIL";

export const FOOD_POST_START = "FOOD:POST_START";
export const FOOD_POST_SUCCESS = "FOOD:POST_SUCCESS";
export const FOOD_POST_FAIL = "FOOD:POST_FAIL";

export const FOOD_DELETE_SUCCESS = "FOOD:DELETE_SUCCESS";
export const FOOD_DELETE_FAIL = "FOOD:DELETE_FAIL";

export const FOOD_UPDATE_SUCCESS = "FOOD:UPDATE_SUCCESS";
export const FOOD_UPDATE_FAIL = "FOOD:UPDATE_FAIL";
