export const USER_POST_SUCCESS = "USER:POST_SUCCESS";
export const USER_POST_FAIL = "USER:POST_FAIL";

export const USER_GET_SUCCESS = "USER:GET_SUCCESS";
export const USER_GET_FAIL = "USER:GET_FAIL";

export const FOOD_NEAREST_SUCCESS = "FOOD:GET_NEAERST_SUCCESS";
export const FOOD_NEAREST_FAIL = "FOOD:GET_NEAERST_FAIL";
export const FOOD_OWN_SUCCESS = "FOOD:GET_OWN_SUCCESS";
export const FOOD_OWN_FAIL = "FOOD:GET_OWN_FAIL";

export const FOOD_POST_SUCCESS = "FOOD:POST_SUCCESS";
export const FOOD_POST_FAIL = "FOOD:POST_FAIL";
