# Generated by Django 3.0.7 on 2020-06-20 09:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import vkapp.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VKUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_id', models.IntegerField()),
                ('first_name', models.TextField()),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('location_coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Location')),
                ('location_title', models.TextField()),
                ('notifications_radius', models.IntegerField(default=1)),
                ('notifications_status', models.BooleanField()),
                ('medal', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_date', models.DateField(auto_now_add=True)),
                ('duration', models.IntegerField(default=5)),
                ('photo_url', models.ImageField(blank=True, upload_to=vkapp.utils.path_and_rename, verbose_name='Изображение')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('status', models.SmallIntegerField(choices=[(0, 'Done'), (1, 'Active'), (2, 'Outdated'), (-1, 'Canceled')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vkapp.VKUser')),
            ],
        ),
    ]
