# Generated by Django 3.0.7 on 2020-06-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
