# Generated by Django 3.0.7 on 2020-06-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkuser',
            name='vk_id',
            field=models.IntegerField(unique=True),
        ),
    ]
