# Generated by Django 3.0.7 on 2020-06-24 19:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkapp', '0002_auto_20200624_1526'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='vkuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='vkuser',
            name='location_coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='vkuser',
            name='location_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
