# Generated by Django 3.0.7 on 2020-06-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkapp', '0002_auto_20200620_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkuser',
            name='medal',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
