# Generated by Django 3.0.7 on 2020-06-24 19:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkapp', '0003_auto_20200624_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='food',
            name='duration',
            field=models.DurationField(verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='food',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата размещения'),
        ),
        migrations.AlterField(
            model_name='food',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Done'), (1, 'Active'), (2, 'Outdated'), (-1, 'Canceled')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='food',
            name='title',
            field=models.TextField(verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='vkuser',
            name='avatar_url',
            field=models.TextField(blank=True, null=True, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='vkuser',
            name='first_name',
            field=models.CharField(max_length=16, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='vkuser',
            name='last_name',
            field=models.CharField(max_length=16, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='vkuser',
            name='location_coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='vkuser',
            name='location_title',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='vkuser',
            name='notifications_radius',
            field=models.IntegerField(default=1, verbose_name='Радиус'),
        ),
        migrations.AlterField(
            model_name='vkuser',
            name='notifications_status',
            field=models.BooleanField(default=True, verbose_name='Статус оповещения'),
        ),
        migrations.AlterField(
            model_name='vkuser',
            name='vk_id',
            field=models.IntegerField(unique=True, verbose_name='VK ID'),
        ),
    ]
