# Generated by Django 3.0.7 on 2020-06-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkapp', '0003_auto_20200620_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkuser',
            name='notifications_status',
            field=models.BooleanField(default=True),
        ),
    ]
