# Generated by Django 3.0.7 on 2020-06-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkapp', '0004_auto_20200620_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkuser',
            name='last_name',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
