# Generated by Django 3.0.7 on 2020-06-25 09:09

from django.db import migrations, models
import vkapp.utils


class Migration(migrations.Migration):

    dependencies = [
        ('vkapp', '0004_auto_20200624_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(upload_to=vkapp.utils.path_and_rename_image, verbose_name='Изображение'),
        ),
    ]
