# Generated by Django 3.0.7 on 2020-06-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkapp', '0005_vkuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkuser',
            name='avatar_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
