# Generated by Django 3.0.7 on 2020-06-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkapp', '0005_auto_20200625_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='duration',
        ),
        migrations.AddField(
            model_name='food',
            name='duration_days',
            field=models.IntegerField(default=5, verbose_name='Продолжительность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
    ]
