# Generated by Django 3.0.7 on 2020-06-26 11:21

from django.db import migrations, models
import vkapp.utils


class Migration(migrations.Migration):

    dependencies = [
        ('vkapp', '0006_auto_20200625_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image_preview',
            field=models.ImageField(blank=True, null=True, upload_to=vkapp.utils.path_and_rename, verbose_name='Предпросмотр'),
        ),
    ]
