# Generated by Django 3.0.7 on 2020-06-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkapp', '0006_auto_20200620_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkuser',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
