# Generated by Django 3.0.7 on 2020-06-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkapp', '0007_auto_20200620_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkuser',
            name='avatar_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
