# Generated by Django 3.0.7 on 2020-06-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkapp', '0007_food_image_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkuser',
            name='city',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='vkuser',
            name='country',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Страна'),
        ),
    ]
