# Generated by Django 3.0.7 on 2020-07-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkapp', '0009_auto_20200626_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='food',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('Active', 'Active'), ('Outdated', 'Outdated'), ('Canceled', 'Canceled')], default='Active', max_length=8, verbose_name='Статус'),
        ),
    ]
