# Generated by Django 3.0.7 on 2020-07-07 18:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vkapp', '0010_auto_20200704_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
